export const studentsData = [
  { name: 'ALANOCA ESQUIVEL JOSE LUIS', firstPartial: 22, secondPartial: 15, finalExam: 29 },
  { name: 'APAZA CALIZAYA ALBA NICOLE', firstPartial: 30, secondPartial: 30, finalExam: 25 },
  { name: 'BALBOA PATTY EDGAR', firstPartial: 24, secondPartial: 20, finalExam: 20 },
  { name: 'CALZADILLA BERNAL JULIO CESAR', firstPartial: 18, secondPartial: 15, finalExam: 22 },
  { name: 'CARI CAMEO ROXANA CAROLA', firstPartial: 27, secondPartial: 15, finalExam: 3 },
  { name: 'CHICHINCA CALLATA JUDITH NOEMI', firstPartial: 19, secondPartial: 17, finalExam: 12 },
  { name: 'CONDORI TANCARA GUSTAVO ENRIQUE', firstPartial: 30, secondPartial: 29, finalExam: 20 },
  { name: 'COPA MAMANI JOEL EDDY', firstPartial: 30, secondPartial: 30, finalExam: 18 },
  { name: 'CRUZ MAMANI EDIL', firstPartial: 24, secondPartial: 15, finalExam: 18 },
  { name: 'HUANDIA TORREZ JOSE ARMANDO', firstPartial: 30, secondPartial: 30, finalExam: 25 },
  { name: 'JIMENEZ GUZMAN ELIAN JUAQUIN', firstPartial: 30, secondPartial: 30, finalExam: 22 },
  { name: 'LIMACHI QUISPE MIJAEL', firstPartial: 27, secondPartial: 29, finalExam: 22 },
  { name: 'LINO RAMOS OSMAR SAUL', firstPartial: 30, secondPartial: 30, finalExam: 24 },
  { name: 'LOZA CAHUAYA RANDOL IDOL', firstPartial: 27, secondPartial: 24, finalExam: 24 },
  { name: 'LUCANA MAMANI JOHN HUBERTH', firstPartial: 28, secondPartial: 18, finalExam: 19 },
  { name: 'MAMANI CALA CELMIRA', firstPartial: 30, secondPartial: 25, finalExam: 21 },
  { name: 'MENDOZA CHOQUE NATALY', firstPartial: 30, secondPartial: 29, finalExam: 30 },
  { name: 'MOSCOSO CASSAPIA MARCO ANTONIO', firstPartial: 30, secondPartial: 30, finalExam: 25 },
  { name: 'PONCE FLORES CARLOS RAMIRO', firstPartial: 0, secondPartial: 0, finalExam: 0 },
  { name: 'QUISPE ORTUÑO ANDREA ABRIL', firstPartial: 30, secondPartial: 15, finalExam: 20 },
  { name: 'ROMERO GAMARRA LUZ DANIELA', firstPartial: 30, secondPartial: 24, finalExam: 21 },
  { name: 'TICONA QUISPE VICTOR', firstPartial: 30, secondPartial: 29, finalExam: 25 },
  { name: 'TICONA SIÑANI ALEJANDRO REYNALDO', firstPartial: 30, secondPartial: 28, finalExam: 25 },
  { name: 'ZUÑIGA CHOCAMANI RUBEN', firstPartial: 13, secondPartial: 3, finalExam: 0 },
  { name: 'ZULETA MAMANI JUAN ARMANDO', firstPartial: 28, secondPartial: 19, finalExam: 18 }
];