export const studentsData = [
  {"name": "ALANOCA ESQUIVEL JOSE LUIS", "firstPartial": 22, "secondPartial": 15, "finalExam": 29, "email": "joseluis.jose9@gmail.com", "fair": 10},
  {"name": "APAZA CALIZAYA ALBA NICOLE", "firstPartial": 30, "secondPartial": 30, "finalExam": 25, "email": "albapazacal03@gmail.com", "fair": 0},
  {"name": "BALBOA PATTY EDGAR", "firstPartial": 24, "secondPartial": 20, "finalExam": 20, "email": "edybalboa76@gmail.com", "fair": 10},
  {"name": "CALZADILLA BERNAL JULIO CESAR", "firstPartial": 18, "secondPartial": 15, "finalExam": 22, "email": "juliocalzadillabernal@gmail.com", "fair": 10},
  {"name": "CARI CAMEO ROXANA CAROLA", "firstPartial": 27, "secondPartial": 15, "finalExam": 3, "email": "carolacameo94@gmail.com", "fair": 0},
  {"name": "CHICHINCA CALLATA JUDITH NOEMI", "firstPartial": 19, "secondPartial": 17, "finalExam": 17, "email": "chichichincacallatanoemi@gmail.com", "fair": 10},
  {"name": "CONDORI TANCARA GUSTAVO ENRIQUE", "firstPartial": 30, "secondPartial": 29, "finalExam": 20, "email": "gustavo.tancara975ce@gmail.com", "fair": 10},
  {"name": "COPA MAMANI JOEL EDDY", "firstPartial": 30, "secondPartial": 30, "finalExam": 18, "email": "JoelCopa01@gmail.com", "fair": 0},
  {"name": "CRUZ MAMANI EDIL", "firstPartial": 24, "secondPartial": 15, "finalExam": 18, "email": "mmnnv@gmail.com", "fair": 10},
  {"name": "HUANDIA TORREZ JOSE ARMANDO", "firstPartial": 30, "secondPartial": 30, "finalExam": 25, "email": "61817641a@gmail.com", "fair": 0},
  {"name": "JIMENEZ GUZMAN ELIAN JUAQUIN", "firstPartial": 30, "secondPartial": 30, "finalExam": 22, "email": "elijan044@gmail.com", "fair": 10},
  {"name": "LIMACHI QUISPE MIJAEL", "firstPartial": 27, "secondPartial": 29, "finalExam": 22, "email": "mijaellimachi@gmail.com", "fair": 10},
  {"name": "LINO RAMOS OSMAR SAUL", "firstPartial": 30, "secondPartial": 30, "finalExam": 24, "email": "osmarlino.223@gmail.com", "fair": 0},
  {"name": "LOZA CAHUAYA RANDOL IDOL", "firstPartial": 27, "secondPartial": 24, "finalExam": 24, "email": "brandolloza@gmail.com", "fair": 0},
  {"name": "LUCANA MAMANI JOHN HUBERTH", "firstPartial": 28, "secondPartial": 18, "finalExam": 19, "email": "huberthlucana.01@gmail.com", "fair": 10},
  {"name": "MAMANI CALA CELMIRA", "firstPartial": 30, "secondPartial": 25, "finalExam": 21, "email": "calcelmi84@gmail.com", "fair": 10},
  {"name": "MENDOZA CHOQUE NATALY", "firstPartial": 30, "secondPartial": 29, "finalExam": 30, "email": "bobsponjamc44@gmail.com", "fair": 10},
  {"name": "MOSCOSO CASSAPIA MARCO ANTONIO", "firstPartial": 30, "secondPartial": 30, "finalExam": 25, "email": "mamc888.mm@gmail.com", "fair": 0},
  {"name": "PONCE FLORES CARLOS RAMIRO", "firstPartial": 0, "secondPartial": 0, "finalExam": 0, "fair": 0},
  {"name": "QUISPE ORTUÑO ANDREA ABRIL", "firstPartial": 30, "secondPartial": 15, "finalExam": 20, "email": "andreaabrilq@gmail.com", "fair": 10},
  {"name": "ROMERO GAMARRA LUZ DANIELA", "firstPartial": 30, "secondPartial": 24, "finalExam": 21, "email": "dany.idrg@gmail.com", "fair": 10},
  {"name": "TICONA QUISPE VICTOR", "firstPartial": 30, "secondPartial": 29, "finalExam": 25, "email": "vikoc22@gmail.com", "fair": 0},
  {"name": "TICONA SIÑANI ALEJANDRO REYNALDO", "firstPartial": 30, "secondPartial": 28, "finalExam": 25, "email": "alejandrortsinani@outlook.com", "fair": 10},
  {"name": "ZUÑIGA CHOCAMANI RUBEN", "firstPartial": 13, "secondPartial": 3, "finalExam": 0, "email": "rubenzuniga235@gmail.com", "fair": 0},
  {"name": "ZULETA MAMANI JUAN ARMANDO", "firstPartial": 28, "secondPartial": 19, "finalExam": 18, "email": "juanes207@gmail.com", "fair": 0},
];